# Angular CSR Build
FROM node:12.14.0 as build

WORKDIR /app

COPY . /app

RUN npm i

RUN npm run build

FROM nginx:latest

COPY --from=build /app/dist/multiapps-v12/browser /usr/share/nginx/html

EXPOSE 80